-- `lua/plugins/` layout
--
-- `require('lazy').setup('plugins')` imports every module in this directory, so
-- adding a plugin only ever means adding (or editing) a file here -- there is
-- no list to register it in.
--
--   blink-cmp.lua        completion engine (nvim-cmp.lua is the disabled predecessor)
--   conform.lua          formatting + format-on-save
--   debug.lua            nvim-dap, dap-ui and the JS/TS adapters
--   discord-presence.lua neocord rich presence
--   editing.lua          text manipulation: surround-ish, comments, indent, dial, autotag
--   git.lua              fugitive, rhubarb
--   gitsigns.lua         gutter signs and hunk actions
--   harpoon.lua          file marks
--   lang.lua             per-language extras: godot, typescript, rust, love2d
--   lint.lua             nvim-lint (disabled -- conform covers the current needs)
--   lsp-config.lua       mason + lspconfig + the LspAttach keymaps
--   mini.lua             mini.ai / mini.surround / mini.statusline
--   obsidian.lua         markdown: obsidian (disabled), render-markdown, preview
--   oil.lua              file manager
--   secrets.lua          cloak.nvim -- hides values in .env files
--   telescope.lua        fuzzy finder and its `<leader>s*` keymaps
--   themes.lua           colorscheme and transparency
--   tmux-nav.lua         seamless split navigation across tmux panes
--   treesitter.lua       parsers, highlighting, textobjects (`main` branch)
--   trouble.lua          diagnostics / references list
--   ufo.lua              folding
--   ui.lua               indent guides, colorizer, todo-comments
--   which-key.lua        leader group documentation
--
-- This file itself intentionally contributes no plugins.
---@module 'lazy'
---@type LazySpec
return {}
